server:
  port: 8081

spring:
  application:
    name: reservas

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

client:
  post:
    baseUrl: http://localhost:8080/api/v1/vinculacion-cliente
    name: vinculacion-cliente

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic


